### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by dinism** [eLearnTK/moodle_local_questionfinder#7]
When option to search is disable, why not disable too the radio buttons? The same to text input.
The button "SEARCH" is disable.
If enabled search, ALL be enabled otherwise ALL disabled.
![imagem](https://user-images.githubusercontent.com/14828021/147386201-e1d66901-f0de-4f1e-ab50-d50481dbdcdc.png)

**Comment by eLearnTK** [comment]
Thank You for the sugestion: radiobuttons and inputbox now only enabled when check "Search in the Question Bank" enabled.
